### PR TITLE
ODATA

### PR DESCRIPTION
**Pull request by beradrian**
ODATA is now a widely spread standard. It will be good to have an out-of-the-box base implementation for it in this great library.

Even though the implementation is not a fully featured one, it can be the basis for future work and I already successfully used in an existing project. So I thought to share it with others.

### CODE REVIEW

**Comment by troyanskiy** [comment]
Hello @beradrian .
Thank you for your PR, it's really nice to have that.
May I ask you also to add some doc's about that to README.MD file.

Thank you!

**Comment by beradrian** [comment]
Thank you for looking into my PR!
I added some documentation in README. Please let me know if anything else is needed.

**Comment by troyanskiy** [comment]
Thanks a lot!

**Comment by troyanskiy** [comment]
I have renamed some interfaces and classes:
`ODATAQuery` -> `IResourceODATAQuery`
`SingleODATAQuery` -> `SingleODATAQuery`
`ODATAResource` -> `ResourceODATA`
`ODATAResourceParamsBase` -> `ResourceODATAParamsBase`
`ODATAResourceParams` -> `ResourceODATAParams`

I have published new version 2.2.0 with your ODATA.

Thanks again for the PR.

**Pull request merged**
